name: 'Create Other Repo Branch Action'

description: 'Github Action to create a new branch on another repository 🆕🚀'

inputs:
    repository_owner:
        description: 'Repository Owner (e.g: octocat)'
        required: true
    repository_name:
        description: 'Repository Name (e.g: my-repo)'
        required: false
    new_branch_name:
        description: 'New branch name created on other repository (e.g: release-*.*.*)'
        required: true
    new_branch_ref:
        description: 'Ref to create the new branch name on other repository (e.g: main)'
        required: false

runs:
  using: "composite"
  steps:
    - name: Clone informed repository
      run: |
        git clone "https://$API_TOKEN_GITHUB@github.com/${{ inputs.repository_owner }}/${{ inputs.repository_name }}.git"
      shell: bash

    - name: Create new branch
      run: |
        cd ${{ inputs.repository_name }}
        git init
        if [ -n "${{ inputs.new_branch_ref }}" ]; then
            git fetch -a
            git checkout ${{ inputs.new_branch_ref }}
        fi
        
        if [ ! -z $(git branch --remotes --list 'origin/${{ inputs.new_branch_name }}') ]; then
            git push origin -d ${{ inputs.new_branch_name }}
        fi
        git pull
        git checkout -b ${{ inputs.new_branch_name }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git push origin ${{ inputs.new_branch_name }}
      shell: bash

branding:
    icon: 'git-branch'
    color: 'blue'
